name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go:
    name: Go lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["~1.21", "~1.20", "~1.19", "~1.18"]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"
      - uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go test
        run: go test -v -race -cover -covermode atomic -coverprofile cover.out ./...

      - name: Run go tool cover
        run: go tool cover -func=cover.out
